version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: farmacia_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - farmacia_data:/var/lib/postgresql/data

volumes:
  farmacia_data: